username: CSCSuser
port: 22
look_for_keys: True
key_filename: /home/lsmo/.ssh/cscs-key
timeout: 60
allow_agent: True
proxy_jump: CSCSuser@ela.cscs.ch
compress: True
gss_host: daint.cscs.ch
load_system_host_keys: True
key_policy: RejectPolicy
use_login_shell: True
safe_interval: 30.0