username: GASPARuser
port: 22
look_for_keys: True
key_filename: /home/user/.ssh/id_ed25519_fidis
timeout: 60
allow_agent: True
compress: True
gss_auth: False
gss_kex: False
gss_deleg_creds: False
gss_host: jed.epfl.ch
load_system_host_keys: True
key_policy: RejectPolicy
use_login_shell: True
safe_interval: 30.0
